name: Secretos

on:
  workflow_dispatch:

env:
  SOLUTION_PATH: src/WisdomPetMedicine.sln
  DOCKERFILE_PATH: src/WisdomPetMedicine.Api/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_PATH
    - name: Build
      run: dotnet build $SOLUTION_PATH --no-restore
    - name: Test
      run: dotnet test $SOLUTION_PATH --no-build --verbosity normal
  docker:
    name: Contenerización con Docker y .NET
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build src --file $DOCKERFILE_PATH --tag rdiazconcha/github-action-esencial:${{ github.run_number }}
    - name: DOCKERIMAGE_FULL
      run: echo $DOCKERIMAGE_NAME
    - uses: docker/login-action@v2
      name: Log in en Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: rdiazconcha/github-action-esencial:${{ github.run_number }}
