name: Runners hospedados - Docker

on:
  workflow_dispatch:
  
jobs:
  docker:
    name: Contenerización con Docker y .NET
    runs-on: [self-hosted, linux]
    steps:
    - name: show
      run: echo $GITHUB_WORKSPACE
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build src/wpm-api --file src/wpm-api/WisdomPetMedicine.Api/Dockerfile --tag github-action-esencial
