name: Runners

on:
  workflow_dispatch:

env:
  SOLUTION_PATH: src/WisdomPetMedicine.sln
  DOCKERFILE_PATH: src/WisdomPetMedicine.Api/Dockerfile

jobs:
  build:
    runs-on: MGR2-BTH203W-UBUNTU
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_PATH
    - name: Build
      run: dotnet build $SOLUTION_PATH --no-restore
    - name: Test
      run: dotnet test $SOLUTION_PATH --no-build --verbosity normal