name: Runners hospedados - Docker

on:
  workflow_dispatch:
  
jobs:
  docker:
    name: Contenerización con Docker y .NET
    runs-on: [self-hosted, windows]
    steps:
    - name: show
      run: echo $GITHUB_WORKSPACE && ls
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build src --file src/WisdomPetMedicine.Api/Dockerfile --tag github-action-esencial
